# Generated by Django 5.1.3 on 2024-12-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_reservation_email_reservation_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
