# Generated by Django 5.1.3 on 2024-12-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_reservation_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='rdv',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
