version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    container_name: django_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules  # Prevent node_modules from being overwritten
    working_dir: /app
    environment:
      - DATABASE_HOST=mysql-rcharkaoui.alwaysdata.net
      - DATABASE_PORT=3306
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: next_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
