services:
  - name: django-backend
    type: web
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn djangoProject1.wsgi"
    envVars:
      - key: SECRET_KEY
        value: "django-insecure-$qgl6nkmr+f9rr$-+p=(vbfg*(2njrbh@4x#m5iwuw_w-e&te$"
      - key: DATABASE_URL
        value: "mysql-rcharkaoui.alwaysdata.net"

  - name: nextjs-frontend
    type: web
    env: node
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: NEXT_PUBLIC_BACKEND_URL
        value: "https://djangonextapp-7.onrender.com"
